package com.softwire.it.cjo.threads;

import java.lang.Thread.UncaughtExceptionHandler;

/**
 * ****************<br>
 * Date: 21/03/2014<br>
 * Author:  michael<br>
 * ****************<br>
 * <br>
 * This abstract class specifies what the stripped down thread scheduler of CJO should provide
 *
 */
public abstract class ThreadScheduler {
	/**
	 * The application's thread scheduler
	 */
	public static final ThreadScheduler INSTANCE = new SimpleThreadScheduler();
	/**
	 * ****************<br>
     * Date: 21/03/2014<br>
     * Author:  michael<br>
     * ****************<br>
 	 * <br>
 	 * This class represents an object symbolising your thread when it was created. Use this in future interactions
 	 * to execute threads.
	 *
	 */
	public abstract static class Task {};
	
	/**
	 * Schedule the given task. It may begin immediately, but in a separate thread.
	 * @param task - the task to be scheduled
	 */
	public abstract void schedule(Task task);
	
	/**
	 * Deschedule the task. This means it will not run strictly after this has call has returned.
	 * The task is not automatically interrupted, so you should do this beforehand if you desire to.
	 * @param task - the task to deschedule
	 */
	public abstract void deschedule(Task task);
	
	/**
	 * Interrupt the given task. This does not deschedule the task, so you should also deschedule the task if you wish
	 * @param task - the task to interrupt
	 */
	public abstract void interrupt(Task task);
	
	/**
	 * Construct a task from the runnable method.
	 * @param task - the task to construct
	 * @return - the Task that will be run (exceptions thrown by the task on its execution are thrown
	 * into the thread which called this!) - not scheduled automatically
	 */
	public abstract Task makeTask(Runnable task);
	
	/**
	 * 
	 * Construct a task from the runnable method.
	 * @param task - the task to construct
	 * @param handler - any uncaught exceptions generated by the task will be thrown to this handler
	 * @return - the Task that will be run - not scheduled automatically
	 */
	public abstract Task makeTask(Runnable task, UncaughtExceptionHandler handler);
}
